
[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false

[net]
tickrate = 60
port = 1212

[game]
hostname = "MyServer"
mapname = "stationstation"
maxplayers = 64
type = 1
welcomemsg = "Welcome to the server!"

[console]
width = 120
height = 60
password = "honk"
